### ISSUE TITLE
upgrading ioredis to v5

### ISSUE THREAD

**Issue by boredland** [quirrel-dev/owl#208]
would you be interested in upgrading? not sure I could, but I could give it a try.

**Comment by Skn0tt** [comment]
I tried upgrading it, and it looks like there's some problems with the new version of https://github.com/stipsan/ioredis-mock that makes some tests fail. Is there a specific need why we should upgrade to v5? If not, I think we're fine on holding out until there is one.

**Comment by boredland** [comment]
I stumbled across two issues:

1. ioredis v4 doesn't support usernames for auth with redis v6 (there is a workaround)
2. my app, which uses ioredis as a transitive dependency, was picking up the wrong version as soon as I installed quirrel. Workaround was to explicitly install the correct version of ioredis.

I know 2. may be be an edge case.

**Comment by Skn0tt** [comment]
was able to fix the bugs. published in v0.15! will update Quirrel now.

**Comment by boredland** [comment]
> was able to fix the bugs. published in v0.15! will update Quirrel now.

That is amazing!
